package com.mudiraj.mudirajfoundation.Models

import com.google.gson.annotations.SerializedName

data class LoginModel(
    @SerializedName("status") val status: Boolean,
    @SerializedName("message") val message: String,
    @SerializedName("data") val response: LoginResponse,
)
data class LoginResponse(
    @SerializedName("id") val id: String?,
    @SerializedName("role") val role: String?,
    @SerializedName("user_id") val user_id: String?,
    @SerializedName("date_of_birth") val date_of_birth: String?,
    @SerializedName("care_of") val care_of: String?,  // <-- nullable
    @SerializedName("full_name") val full_name: String?,
    @SerializedName("gender") val gender: String?,
    @SerializedName("email") val email: String?,
    @SerializedName("password") val password: String?,
    @SerializedName("password_hit") val password_hit: String?,
    @SerializedName("phone") val phone: String?,
    @SerializedName("image") val image: String?,
    @SerializedName("business_name") val business_name: String?,
    @SerializedName("full_address") val full_address: String?,
    @SerializedName("state") val state: String?,
    @SerializedName("constituencies") val constituencies: String?,
    @SerializedName("mandal") val mandal: String?,
    @SerializedName("ward") val ward: String?,
    @SerializedName("pin_code") val pin_code: String?,
    @SerializedName("current_occupation") val current_occupation: String?,
    @SerializedName("organization_company") val organization_company: String?,
    @SerializedName("designation") val designation: String?,
    @SerializedName("work_location") val work_location: String?,
    @SerializedName("permanent_address") val permanent_address: String?,
    @SerializedName("membership_type") val membership_type: String?,
    @SerializedName("amount") val amount: String?,
    @SerializedName("facebook_profile") val facebook_profile: String?,
    @SerializedName("facebook_followers") val facebook_followers: String?,
    @SerializedName("instagram_profile") val instagram_profile: String?,
    @SerializedName("instagram_followes") val instagram_followes: String?,
    @SerializedName("twitter_x_profile") val twitter_x_profile: String?,
    @SerializedName("twitter_x_follwers") val twitter_x_follwers: String?,
    @SerializedName("linkedin_profile") val linkedin_profile: String?,
    @SerializedName("youtube_channel") val youtube_channel: String?,
    @SerializedName("youtube_followers") val youtube_followers: String?,
    @SerializedName("whatsapp_number") val whatsapp_number: String?,
    @SerializedName("telegram_username_channel") val telegram_username_channel: String?,
    @SerializedName("skills_interests") val skills_interests: String?,
    @SerializedName("volunteer_experience") val volunteer_experience: String?,
    @SerializedName("affiliated_organizations") val affiliated_organizations: String?,
    @SerializedName("marital_status") val marital_status: String?,
    @SerializedName("blood_group") val blood_group: String?,
    @SerializedName("two_wheeler") val two_wheeler: String?,
    @SerializedName("four_wheeler") val four_wheeler: String?,
    @SerializedName("created_at") val created_at: String?,
    @SerializedName("updated_at") val updated_at: String?,
    @SerializedName("status") val status: String?,
    @SerializedName("total_users") val total_users: String?

)